<?xml version="1.0"?>
<!-- ***************************************************************************
  See the NOTICE file distributed with this work for additional information
  regarding copyright ownership.
  
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
  
    http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
**************************************************************************** -->
<!DOCTYPE Automat [
	<!ELEMENT Automat (Podatci_Sklopa,Stanje*,Prijelaz*)>
	<!ELEMENT Podatci_Sklopa (Ime,Tip,Interfac,Pocetno_Stanje,Reset,Clock,Sirina,Visina)>
	<!ELEMENT Prijelaz (Iz,U,Pobuda,Izlaz?)>
	<!ELEMENT Stanje (Ime,Izlaz?,Ox,Oy,Else,ElseIzlaz?)>
	<!ELEMENT Ime (#PCDATA)>
	<!ELEMENT Tip (#PCDATA)>
	<!ELEMENT Broj_Bitova_Ulaz (#PCDATA)>
	<!ELEMENT Broj_Bitova_Izlaz (#PCDATA)>
	<!ELEMENT Iz (#PCDATA)>
	<!ELEMENT U (#PCDATA)>
	<!ELEMENT Izlaz (#PCDATA)>
	<!ELEMENT Ox (#PCDATA)>
	<!ELEMENT Oy (#PCDATA)>
	<!ELEMENT Pobuda (#PCDATA)>
]>
<Automat>

	<Podatci_Sklopa>
		<Ime>Automat1</Ime>
		<Tip>Moore</Tip>
		<Interfac>a in std_logic
b out std_logic
		</Interfac>
		<Pocetno_Stanje>A</Pocetno_Stanje>
		<Reset>1</Reset>
		<Clock>falling_edge</Clock>
		<Sirina>300</Sirina>
		<Visina>300</Visina>
	</Podatci_Sklopa>

	<Stanje>
		<Ime>A</Ime>
		<Izlaz>0</Izlaz>
		<Ox>30</Ox>
		<Oy>30</Oy>
		<Else>A</Else>
	</Stanje>

	<Stanje>
		<Ime>B</Ime>
		<Izlaz>1</Izlaz>
		<Ox>100</Ox>
		<Oy>100</Oy>
		<Else>A</Else>
	</Stanje>

	<Stanje>
		<Ime>C</Ime>
		<Izlaz>1</Izlaz>
		<Ox>30</Ox>
		<Oy>100</Oy>
		<Else>B</Else>
	</Stanje>

	<Prijelaz>
		<Iz>A</Iz>
		<U>B</U>
		<Pobuda>1</Pobuda>
	</Prijelaz>

	<Prijelaz>
		<Iz>A</Iz>
		<U>C</U>
		<Pobuda>0</Pobuda>
	</Prijelaz>

	<Prijelaz>
		<Iz>B</Iz>
		<U>A</U>
		<Pobuda>1</Pobuda>
	</Prijelaz>

	<Prijelaz>
		<Iz>B</Iz>
		<U>C</U>
		<Pobuda>0</Pobuda>
	</Prijelaz>

	<Prijelaz>
		<Iz>C</Iz>
		<U>C</U>
		<Pobuda>0</Pobuda>
	</Prijelaz>

	<Prijelaz>
		<Iz>C</Iz>
		<U>B</U>
		<Pobuda>1</Pobuda>
	</Prijelaz>
</Automat>
