<?xml version="1.0"?>
<!DOCTYPE Automat [
	<!ELEMENT Automat (Podatci_Sklopa,Stanje*,Prijelaz*)>
	<!ELEMENT Podatci_Sklopa (Ime,Tip,Interfac,Pocetno_Stanje)>
	<!ELEMENT Prijelaz (Iz,U,Pobuda,Izlaz?)>
	<!ELEMENT Stanje (Ime,Izlaz?,Ox,Oy)>
	<!ELEMENT Ime (#PCDATA)>
	<!ELEMENT Tip (#PCDATA)>
	<!ELEMENT Broj_Bitova_Ulaz (#PCDATA)>
	<!ELEMENT Broj_Bitova_Izlaz (#PCDATA)>
	<!ELEMENT Iz (#PCDATA)>
	<!ELEMENT U (#PCDATA)>
	<!ELEMENT Izlaz (#PCDATA)>
	<!ELEMENT Ox (#PCDATA)>
	<!ELEMENT Oy (#PCDATA)>
	<!ELEMENT Pobuda (#PCDATA)>
]>
<Automat>

	<Podatci_Sklopa>
		<Ime>Automat1</Ime>
		<Tip>Moore</Tip>
		<Interfac>
		a:in 1
b:out 1
		</Interfac>
		<Pocetno_Stanje>A</Pocetno_Stanje>
	</Podatci_Sklopa>

	<Stanje>
		<Ime>A</Ime>
		<Izlaz>0</Izlaz>
		<Ox>30</Ox>
		<Oy>30</Oy>
	</Stanje>

	<Stanje>
		<Ime>B</Ime>
		<Izlaz>1</Izlaz>
		<Ox>100</Ox>
		<Oy>100</Oy>
	</Stanje>

	<Stanje>
		<Ime>C</Ime>
		<Izlaz>1</Izlaz>
		<Ox>30</Ox>
		<Oy>100</Oy>
	</Stanje>

	<Prijelaz>
		<Iz>A</Iz>
		<U>B</U>
		<Pobuda>1</Pobuda>
	</Prijelaz>

	<Prijelaz>
		<Iz>A</Iz>
		<U>C</U>
		<Pobuda>0</Pobuda>
	</Prijelaz>

	<Prijelaz>
		<Iz>B</Iz>
		<U>A</U>
		<Pobuda>1</Pobuda>
	</Prijelaz>

	<Prijelaz>
		<Iz>B</Iz>
		<U>C</U>
		<Pobuda>0</Pobuda>
	</Prijelaz>

	<Prijelaz>
		<Iz>C</Iz>
		<U>C</U>
		<Pobuda>0</Pobuda>
	</Prijelaz>

	<Prijelaz>
		<Iz>C</Iz>
		<U>B</U>
		<Pobuda>1</Pobuda>
	</Prijelaz>
</Automat>